# --------
# using scipy, it's kinda big but that should not be a problem
# base-notebook lacks at least numpy, widgets, so...
FROM nbhosting/scipy-notebook


# --------
RUN pip install plotly mpld3


#RUN conda install -y mpld3
RUN pip install mpld3

